email and password rules
GenForm/GenForm pull request #20
Opened 2024-01-05 20:28 UTC by natdoly

2024-01-05 20:35 UTC, Jathoosh requested changes

2024-01-05 20:35 UTC, Jathoosh commented on GenForm-NPM/Features/password.js
Tu imposes tes propres règles, certes secure, sur les mots de passes, mais on ne peut pas, faut laisser le choix finale au dev utilisant le package.
Egalement, cette fonctionnalité est déjà disponible via "pattern" sur le champ de type "password"
![image](https://github.com/GenForm/GenForm/assets/73128006/82b63f3e-77f8-4621-853a-d478ae62c5b1)

2024-01-05 20:35 UTC, Jathoosh commented on GenForm-NPM/Features/email.js
Pareil que pour password le pattern peut être défini par le dev vie le champ "pattern"
Egalement par défaut, le type "email" permet d'avoir un pattern déjà défini pour les emails
![image](https://github.com/GenForm/GenForm/assets/73128006/10d9c48e-e1a6-4585-95c8-3bcaf20bf39b)

2024-01-05 20:44 UTC, natdoly commented on GenForm-NPM/Features/password.js
Ah oui

2024-01-06 10:26 UTC, natdoly commented on GenForm-NPM/Features/password.js
le pattern doit être directement dans la definition de l'email ou dans la clé features ?

2024-01-07 11:41 UTC, RomainMarques commented
Tu as pu tester que tes changements fonctionnaient?

2024-01-07 12:45 UTC, natdoly commented
> Tu as pu tester que tes changements fonctionnaient?

Oui, ça fonctionne , j'ai testé avec deux type password :  la vérification fonctionne bien, pareil avec le type email

2024-01-07 12:46 UTC, RomainMarques submitted a review, later dismissed

2024-01-07 12:49 UTC, natdoly commented on GenForm-NPM/Features/email.js
> +    if (this.value.includes('@') && this.value.includes('.')) {
Après un nouveau test, y a un soucis sur ce point là. Je fix ça

2024-01-07 13:13 UTC, Jathoosh commented on GenForm-NPM/Features/email.js
> +    if (this.value.includes('@') && this.value.includes('.')) {
Mais t'as pas sup email.js ?

2024-01-07 13:17 UTC, natdoly commented on GenForm-NPM/Features/email.js
> +    if (this.value.includes('@') && this.value.includes('.')) {
si 🤔. Bon bah @RomainMarques ce fichier est à ignorer vu qu’il n’y est plus. La on se concentre uniquement sur la bonne écriture sur deux champs qui doivent être liés

2024-01-07 23:34 UTC, Jathoosh requested changes

2024-01-07 23:34 UTC, Jathoosh commented on GenForm-NPM/Features/generics.js
> +    const errorMessage = document.createElement('p')
Il va falloir changer le json pour lui demander l'id de l'élément qui sera modifié plutôt, là en créant un élément "p", on a aucun contrôle sur sa position dans le formulaire

2024-01-07 23:34 UTC, Jathoosh commented on GenForm-NPM/Features/generics.js
> +    const keyInput = form.querySelector('input[name="' + key + '"]')
Bon, ça change pas grand je choses je suppose mais getElementByName marche pas ?

2024-01-07 23:34 UTC, Jathoosh commented on GenForm-NPM/Features/generics.js
> +          throw new Error("inputs don't match")
C'est une fonction de vérification pour l'utilisateur finale du formulaire, pas pour le dev, une erreur au milieu de nulle part n'est pas forcément la meilleur solution. La modification du bloc de texte est amplement suffisante (faut juste redonner le contrôle au dev utilisant le package).
L'un des plus grand fléau du javascript, c'est qu'il ne te prévient jamais quand la fonction veut te balancer une erreur (et là c'est le cas)

2024-01-08 09:26 UTC, natdoly commented on GenForm-NPM/Features/generics.js
> +          throw new Error("inputs don't match")
que veux tu dire par "la modification du bloc de texte est amplement suffisante" ?

2024-01-08 10:25 UTC, Jathoosh commented on GenForm-NPM/Features/generics.js
> +          throw new Error("inputs don't match")
Le tag <p>, vu que tu le fais apparaître ou non
Également, la possibilité dans le json, de choisir le message à afficher (s'il y en a pas, en avoir un par défaut directement dans le code)

2024-01-08 10:32 UTC, natdoly commented on GenForm-NPM/Features/generics.js
> +          throw new Error("inputs don't match")
AH OK

2024-01-10 11:23 UTC, Jathoosh requested changes

2024-01-10 11:23 UTC, Jathoosh commented on GenForm-NPM/Features/generics.js
> +        return
Break pas Return

2024-01-10 11:26 UTC, Jathoosh requested changes

2024-01-10 11:26 UTC, Jathoosh commented on GenForm-NPM/Features/generics.js
> +        valueInput.setCustomValidity(errorMessage.textContent)
Pourquoi cette ligne ? ça va pas instant activer le popup ?

2024-01-10 11:26 UTC, Jathoosh commented on GenForm-NPM/Features/generics.js
> +    form.addEventListener('input', function () {
Pourquoi c'est en dehors du switch case ?

2024-01-10 11:34 UTC, natdoly commented on GenForm-NPM/Features/generics.js
> +        valueInput.setCustomValidity(errorMessage.textContent)
ça plante sans ce rajout. Ca s'active au moment du clique sur login

2024-01-10 11:37 UTC, natdoly commented on GenForm-NPM/Features/generics.js
> +    form.addEventListener('input', function () {
erreur de ma part

2024-01-10 12:48 UTC, Jathoosh approved these changes
lgtm

2024-01-10 13:22 UTC, merged