Standardisation des tests + Modification du test Cypress
GenForm/GenForm pull request #21
Opened 2024-01-06 13:25 UTC by RomainMarques

Nouveau format du test React : 

<img width="1186" alt="Capture d’écran 2024-01-06 à 14 19 31" src="https://github.com/GenForm/GenForm/assets/77971683/7e1df5a8-dba3-4e71-9e7e-3e6fef5fe297">

Test cypress : 
<img width="1186" alt="Capture d’écran 2024-01-06 à 14 18 18" src="https://github.com/GenForm/GenForm/assets/77971683/ca74a869-618d-42f4-8cbb-9c87f384b1ab">

2024-01-06 14:06 UTC, RomainMarques commented on GenForm-Tests/Vanilla/index.js
> +import GenForm from 'https://cdn.jsdelivr.net/npm/@genform/core@0.1.9/+esm'
J'ai modifié la ligne d'import pck avant ça me mettait que une erreur type "ambiguous declaration" ce qui faisait crasher le test cypress

2024-01-06 14:57 UTC, Jathoosh requested changes

2024-01-06 14:57 UTC, Jathoosh commented on GenForm-Tests/Vanilla/package.json
Le but du vanilla est justement de ne pas utiliser Node mais une url en passant par Unpkg 
La partie node qui est présente dans le dossier est juste là pour faciliter le lancement du projet en passant par le package serve
Tu peux faire npm uninstall @genform/core ?

2024-01-06 14:57 UTC, Jathoosh commented on GenForm-Tests/Vanilla/index.js
> +import GenForm from 'https://cdn.jsdelivr.net/npm/@genform/core@0.1.9/+esm'
Il faudrait trouver une autre solution pour régler ce problème parce que dans la suite du projet, avec le package complet je continue à utiliser unpkg qui est beaucoup plus simple d'utilisation et ne change pas les arguments
Pour l'instant ne t'occupes pas du la partie Vanilla, tu peux revert les changements sur Vanilla ?

2024-01-06 14:57 UTC, Jathoosh commented on GenForm-Tests/React/test.json
Peut-être déplacer ce fichier également, dans le cas de la généralisation du cypress

2024-01-06 14:57 UTC, Jathoosh commented on GenForm-Tests/React/cypress/e2e/spec.cy.js
Il faudrait peut-être changer l'emplacement du fichier/dossier afin qu'il s'applique sur les trois projets et pas uniquement react, sauf si j'ai mal compris

2024-01-06 15:01 UTC, RomainMarques commented on GenForm-Tests/React/test.json
C'est tout le dossier cypress qu'il va falloir déplacer

2024-01-06 15:02 UTC, RomainMarques commented on GenForm-Tests/Vanilla/index.js
> +import GenForm from 'https://cdn.jsdelivr.net/npm/@genform/core@0.1.9/+esm'
C'est la seule solution que j'ai trouvé pour le coup, sinon j'ai une erreur

2024-01-06 15:05 UTC, Jathoosh commented on GenForm-Tests/Vanilla/index.js
> +import GenForm from 'https://cdn.jsdelivr.net/npm/@genform/core@0.1.9/+esm'
Je verrai après avoir fini le package complete du coup, tu peux screen l'erreur et l'envoyer sur discord ?

2024-01-09 16:19 UTC, RomainMarques commented on GenForm-Tests/Vanilla/package.json
Je te réponds ici pour le commentaire où tu me demandes quelle est l'erreur avec unpkg :

<img width="422" alt="Capture d’écran 2024-01-09 à 17 18 45" src="https://github.com/GenForm/GenForm/assets/77971683/21719a85-dd1c-4fc3-ad66-0a3f03e5e6ca">

Et sur la version web j'ai aussi une erreur avec la version vanilla de tests :

<img width="1160" alt="Capture d’écran 2024-01-09 à 17 19 36" src="https://github.com/GenForm/GenForm/assets/77971683/d534438c-a672-4fec-a2c6-664c48b735df">

2024-01-09 20:20 UTC, Jathoosh commented on GenForm-Tests/Vanilla/package.json
Okay got it, suffit de reverse à la version 0.1.5, j'ai merdé avec Babel, plus jamais je le réutilise

2024-01-09 20:20 UTC, Jathoosh commented on GenForm-Tests/Vanilla/package.json
Mb haha

2024-01-09 20:47 UTC, RomainMarques commented on GenForm-Tests/Vanilla/package.json
Ok je regarderai ça demain et je te tiendrai au courant pour savoir si ça marche

2024-01-10 15:37 UTC, RomainMarques commented
J'ai modifié le dossier cypress, intéressant de noter qu'il n'y a pas besoin de package.json pour lancer cypress, juste la commande `npx cypress open` suffit.

2024-01-11 07:22 UTC, Jathoosh approved these changes
lgtm

2024-01-11 07:25 UTC, merged