Sécurité et vérification du json avant création du formulaire
GenForm/GenForm pull request #5
Opened 2023-12-26 22:28 UTC by natdoly

- verification des doublons
- vérification du format correct d'un JSON

2023-12-26 22:33 UTC, Jathoosh reviewed
Mob review ?

2023-12-26 22:39 UTC, natdoly commented
> Mob review ?

?

2023-12-26 22:39 UTC, Jathoosh commented
Faire une présentation des changements en reu x)

2023-12-26 22:39 UTC, Jathoosh commented
Mais plus sérieusement

2023-12-26 22:45 UTC, Jathoosh requested changes
Les changements n'ont pas été faits sur le bon fichier : 
Le bon fichier : genform-npm>Core>index.js
Btw hésite pas à pull les changements du main

2023-12-27 12:21 UTC, Jathoosh requested changes
Et en fait ton block if ne prends pas dans sa totalité la création du formulaire

2023-12-27 15:44 UTC, Jathoosh approved these changes

2023-12-27 15:45 UTC, merged